[workspace]

members = ["akka-persistence-rs", "akka-persistence-rs-filelog"]

[workspace.dependencies]
async-stream = "0.3.3"
async-trait = "0.1.72"
env_logger = "0.10.0"
serde = "1.0.151"
streambed = { git = "https://github.com/streambed/streambed-rs.git", rev = "4b7e1561666bc1860339d27f5abf9be246ef5ad9" }
streambed-logged = { git = "https://github.com/streambed/streambed-rs.git", rev = "4b7e1561666bc1860339d27f5abf9be246ef5ad9" }
test-log = "0.2.11"
tokio = "1.23.0"
tokio-stream = "0.1.14"
