[package]
name = "akka-projection-rs-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
tokio-stream = { workspace = true }

akka-persistence-rs = { path = "../akka-persistence-rs" }
akka-projection-rs = { path = "../akka-projection-rs" }
