[package]
name = "akka-projection-rs-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
ciborium = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
streambed = { workspace = true }
streambed-storage = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }

akka-persistence-rs = { path = "../akka-persistence-rs" }
akka-projection-rs = { path = "../akka-projection-rs" }
