name: Dependency License Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # At 00:00 on saturdays

permissions:
  contents: read

jobs:
  fossa:
    name: Fossa
    runs-on: ubuntu-22.04
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.0
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.3
        uses: coursier/cache-action@d1039466d0812d6370649b9afb02bbf5f646bacf

      - name: Set up JDK 11
        # https://github.com/coursier/setup-action/releases
        # v1.3.4
        uses: coursier/setup-action@48280172a2c999022e42527711d6b28e4945e6f0
        with:
          jvm: temurin:1.11

      - name: FOSSA policy check
        run: |-
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa analyze
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}"
