name: Dependency License Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6' # At 00:00 on saturdays

permissions:
  contents: read

jobs:
  fossa:
    name: Fossa
    runs-on: ubuntu-22.04
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.0
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: Update Rust
        run: |
          rustup update

      - name: Cache Rust
        # https://github.com/Swatinem/rust-cache/releases
        # v2.7.0
        uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43

      - name: FOSSA policy check
        run: |-
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa analyze
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}"
