name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

env:
  CARGO_TERM_COLOR: always
  PROTOC_VERSION: 3.23.4

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      RUSTFLAGS: -Dwarnings

    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: |
        rustup update
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - uses: Swatinem/rust-cache@v2

    - name: test
      run: |
        cargo clippy --tests
        cargo fmt -- --check
        cargo test
