name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      RUSTFLAGS: -Dwarnings

    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: |
        rustup update
    - uses: Swatinem/rust-cache@v2

    - name: test
      run: |
        cargo clippy --tests
        cargo fmt -- --check
        cargo test
