name: Test

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]

env:
  CARGO_TERM_COLOR: always
  PROTOC_VERSION: 3.23.4

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: -Dwarnings

    steps:
    - name: Checkout
      # https://github.com/actions/checkout/releases
      # v4.1.1
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Update Rust
      run: |
        rustup update

    - name: Install protoc
      # https://github.com/taiki-e/install-action/releases
      # v2.20.3
      uses: taiki-e/install-action@47d27149ff6b3422864ec504071d5cc7873d642e
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}

    - name: Cache Rust
      # https://github.com/Swatinem/rust-cache/releases
      # v2.7.0
      uses: Swatinem/rust-cache@a95ba195448af2da9b00fb742d14ffaaf3c21f43

    - name: test
      run: |
        cargo clippy --tests
        cargo fmt -- --check
        cargo test
